services:
  - type: web
    name: nublack-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: nublack12.com
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        fromDatabase:
          name: DB_USER
      - key: DB_PASS
        fromDatabase:
          name: DB_PASS
      - key: DB_NAME
        fromDatabase:
          name: DB_NAME
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://tu-frontend.com
